### ISSUE TITLE
ignoring forks

### ISSUE THREAD

**Issue by badar-chachar** [oscarpobletes/GitHubMines#1]
How can I modify the query to ignore/exclude the forks from the results?

**Comment by oscarpobletes** [comment]
Hi @badar-chachar! To accomplish that, you will need to make two simple modifications in the index.js file:

1. Remove the 'forkCount' field from the query to ensure it's not included when fetching the data.

2. Eliminate the 'forks' property from the 'formattedResults' data structure to ensure it's excluded from the final output.

Let me know if this helps!

**Comment by badar-chachar** [comment]
Hello @oscarpobletes, thanks for the prompt reply.  Removing 'forkCount' and 'forks' doesn't impact the query results, it returns the same number of repositories.  
Can we explicitly specify 'fork=false' in the query? Or something similar?

**Comment by ksegla** [comment]
Hi @badar-chachar 
It looks like that possibility is a recent addition (March 2023) to Github search results. see here: 

https://github.com/orgs/community/discussions/39870#discussioncomment-5294549

and here:

https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#is-qualifier

Normally you only need to add "NOT is:fork" to the search query in the command line. 

Let us know how it goes. Later today, I will test it myself.

**Comment by badar-chachar** [comment]
@ksegla I added `NOT is:fork` to the query string as given below,

`query ($searchQuery: String!, $first: Int, $after: String) {
  search(query: $searchQuery, NOT is:fork, type: REPOSITORY, first: $first, after: $after)`
and it gives error `Error: Parse error on "is" (IDENTIFIER) at [2, 35]`

let me know if `NOT is:fork` is to be added somewhere else in the query.

**Comment by badar-chachar** [comment]
@ksegla you were right, passing `not is:fork` via command line does the trick.

`node index.js --query "smart contract not is:fork"`

**Comment by ksegla** [comment]
Great! 
Closing the issue then.
